name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev
        
    - name: Install Buildozer
      run: pip install buildozer
        
    - name: Create buildozer.spec
      run: |
        echo "[app]
        title = FTP Messenger
        package.name = ftpmessenger
        package.domain = org.ftp
        version = 1.0
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        requirements = python3, kivy, ftplib
        orientation = portrait" > buildozer.spec
        
    - name: Build APK
      run: |
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FTP-Messenger-APK
        path: bin/*.apk
