name: Build Android APK
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zlib1g-dev openjdk-17-jdk
        pip install buildozer cython
        
    - name: Setup Android SDK and accept licenses
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk
        mkdir -p ~/.android
        touch ~/.android/repositories.cfg
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip -d ~/.buildozer/android/platform/android-sdk/
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/bin/sdkmanager --licenses
        ~/.buildozer/android/platform/android-sdk/cmdline-tools/bin/sdkmanager "build-tools;34.0.0" "platforms;android-34"
        
    - name: Build APK
      run: |
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FTP-Messenger-APK
        path: bin/*.apk
