name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libsqlite3-dev \
          libffi-dev \
          libssl-dev \
          python3-venv \
          python3-dev \
          build-essential \
          wget

    - name: Create and activate virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install Buildozer and dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install wheel
        pip install setuptools==65.5.0
        pip install cython==0.29.19
        pip install buildozer
        pip install kivy==2.3.0

    - name: Setup Android SDK correctly
      run: |
        # Создаем директории
        mkdir -p ~/.android
        mkdir -p ~/.buildozer/android/platform
        
        # Принимаем лицензии
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > ~/.android/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> ~/.android/android-sdk-license
        echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> ~/.android/android-sdk-license
        
        # Скачиваем Command Line Tools в правильную директорию
        cd ~/.buildozer/android/platform
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
        unzip -q commandlinetools-linux-8512546_latest.zip
        rm commandlinetools-linux-8512546_latest.zip
        
        # Создаем правильную структуру директорий для Android SDK
        mkdir -p android-sdk/cmdline-tools
        mv cmdline-tools android-sdk/cmdline-tools/latest
        
        # Устанавливаем platform-tools и build-tools
        yes | android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=android-sdk "platform-tools" "build-tools;34.0.0" "platforms;android-33"
        
        # Проверяем установку
        echo "=== SDK Manager check ==="
        ls -la android-sdk/cmdline-tools/latest/bin/sdkmanager || echo "sdkmanager not found"
        
        echo "=== Platform tools ==="
        ls -la android-sdk/platform-tools/ || echo "Platform tools not found"
        
        echo "=== Build tools ==="
        ls -la android-sdk/build-tools/34.0.0/ || echo "Build tools not found"

    - name: Fix Buildozer configuration
      run: |
        # Создаем symlink чтобы Buildozer нашел SDK в ожидаемом месте
        mkdir -p ~/.buildozer/android/platform/android-sdk
        ln -sf ~/.buildozer/android/platform/android-sdk ~/.buildozer/android/platform/android-sdk
        
        echo "=== Fixed SDK structure ==="
        ls -la ~/.buildozer/android/platform/

    - name: Build APK with corrected paths
      run: |
        source venv/bin/activate
        
        # Устанавливаем правильные переменные окружения
        export ANDROID_HOME=~/.buildozer/android/platform/android-sdk
        export ANDROID_SDK_ROOT=~/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/34.0.0:$PATH
        
        echo "=== PATH ==="
        echo $PATH
        
        echo "=== SDK Manager check ==="
        which sdkmanager || echo "sdkmanager not in PATH"
        
        echo "=== Starting build ==="
        timeout 1800 buildozer -v android debug 2>&1 | tee full_build.log

    - name: Analyze build results
      run: |
        echo "=== Build status ==="
        if [ ${PIPESTATUS[0]} -eq 0 ]; then
          echo "Build completed successfully!"
        else
          echo "Build failed or timed out"
        fi
        
        echo "=== Error analysis ==="
        grep -i "error\|fail\|exception\|sdkmanager" full_build.log | head -20 || echo "No obvious errors found"
        
        echo "=== APK search ==="
        find . -name "*.apk" -type f 2>/dev/null || echo "No APK files found"

    - name: Upload build log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: full_build.log

    - name: Upload APK if exists
      if: always()
      run: |
        mkdir -p artifacts
        APK_FILES=$(find . -name "*.apk" -type f 2>/dev/null)
        
        if [ -n "$APK_FILES" ]; then
          echo "Found APK files: $APK_FILES"
          cp $APK_FILES artifacts/
          ls -la artifacts/
        else
          echo "No APK files found"
          # Создаем debug информацию
          echo "Build completed but no APK found" > artifacts/debug.txt
          echo "=== Buildozer directories ===" >> artifacts/debug.txt
          find .buildozer -name "*" -type d | head -10 >> artifacts/debug.txt
        fi

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: artifacts/*.apk

    - name: Upload debug info
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: debug-info
        path: artifacts/debug.txt
