name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev
        
    - name: Install Android SDK and accept licenses
      run: |
        mkdir -p ~/.android-sdk
        cd ~/.android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools tools
        # Принимаем лицензии автоматически
        yes | ./tools/bin/sdkmanager --sdk_root=. --licenses
        ./tools/bin/sdkmanager --sdk_root=. "platform-tools" "build-tools;34.0.0" "platforms;android-33"
        echo "ANDROID_SDK_ROOT=$HOME/.android-sdk" >> $GITHUB_ENV
        echo "$HOME/.android-sdk/platform-tools" >> $GITHUB_PATH
        
    - name: Install Python dependencies
      run: |
        pip install buildozer
        pip install cython
        
    - name: Create buildozer.spec
      run: |
        echo "[app]
        title = FTP Messenger
        package.name = ftpmessenger
        package.domain = org.ftp
        version = 1.0
        source.dir = .
        source.include_exts = py,png,jpg,kv,atlas
        requirements = python3, kivy, ftplib
        orientation = portrait
        android.sdk_path = $HOME/.android-sdk" > buildozer.spec
        
    - name: Build APK
      run: |
        buildozer android debug
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FTP-Messenger-APK
        path: bin/*.apk
