name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          zip \
          unzip \
          openjdk-17-jdk \
          python3-pip \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libsqlite3-dev \
          libffi-dev \
          libssl-dev

    - name: Install Buildozer and dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer
        pip install cython==0.29.33
        pip install kivy

    - name: Build APK with verbose logging
      run: |
        export ANDROID_HOME=~/.buildozer/android/platform/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        
        # Полная очистка перед сборкой
        buildozer android clean 2>/dev/null || true
        rm -rf .buildozer/android/platform/build-*
        rm -rf bin/
        
        # Сборка с подробным логированием
        buildozer -v android debug 2>&1 | tee full_build.log
        
        # Проверяем результат
        if [ $? -eq 0 ]; then
          echo "Build successful!"
          echo "=== Bin directory contents ==="
          ls -la bin/ || echo "bin directory not found"
          echo "=== All APK files ==="
          find . -name "*.apk" -type f
        else
          echo "Build failed! Full log:"
          cat full_build.log
          echo "=== Error summary ==="
          grep -i "error\|fail\|exception" full_build.log | head -20
          exit 1
        fi

    - name: Show build log
      if: always()
      run: |
        echo "=== FULL BUILD LOG ==="
        cat full_build.log || echo "No log file found"
        echo "=== END LOG ==="

    - name: Find and prepare APK
      run: |
        echo "=== Searching for APK files ==="
        find . -name "*.apk" -type f
        
        # Создаем artifacts directory
        mkdir -p artifacts
        
        # Копируем все найденные APK файлы
        if find . -name "*.apk" -type f | grep -q .; then
          echo "APK files found:"
          find . -name "*.apk" -type f -exec cp {} artifacts/ \;
          ls -la artifacts/
        else
          echo "No APK files found anywhere!"
          echo "=== Buildozer directories ==="
          find .buildozer -name "*.apk" -type f 2>/dev/null || echo "No APK in .buildozer"
          exit 1
        fi

    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: artifacts/*.apk

    - name: Upload build log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: full_build.log
