name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Build APK with Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        buildozer_version: stable
        requirements: python3,kivy,ftplib
        package_name: com.ftp.messenger
        app_name: FTP Messenger
        orientation: portrait
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: FTP-Messenger-APK
        path: bin/*.apk
